import React,{useMemo,useRef,useState} from 'react'
import {Box,Building2,CalendarDays,ClipboardCheck,FileUp,LibraryBig,PanelLeft,ReceiptText,Ruler,Save,Settings2,WalletCards} from 'lucide-react'
import ThreeViewport from './ThreeViewport'
import {createFromLibrary,library,materials} from './library'
import {inspectDrawing,projectFromStrut} from './importers'
import {downloadIfc,mergeIfc,projectFromIfc} from './ifc'
import type {Measurement,RJPStudioStructurePackage,SourceDrawing,StudioElement,StudioProject,WorkItem} from './types'

type Page='model'|'library'|'sources'|'mqt'|'budget'|'planning'|'measurements'|'specs'
const now=()=>new Date().toISOString();const blank=():StudioProject=>({id:`P-${Date.now()}`,name:'Novo Projeto',location:'',solution:'traditional',elements:[],createdAt:now(),updatedAt:now()})
const eur=(v:number)=>v.toLocaleString('pt-PT',{style:'currency',currency:'EUR'});const n=(v:any)=>Number(v)||0
const basePrice:Record<string,number>={column:420,beam:360,slab:82,footing:520,wall:58,window:650,door:390,roof:105,gutter:28,pipe:19,stair:900,furniture:250,fixture:160}
function qUnit(e:StudioElement){if(['wall','slab','roof'].includes(e.type))return{unit:'m²',qty:e.type==='wall'?e.size.x*e.size.z:e.size.x*e.size.y};if(['beam','gutter','pipe'].includes(e.type))return{unit:'m',qty:e.type==='pipe'?e.size.z:e.size.x};if(e.type==='footing')return{unit:'m³',qty:e.size.x*e.size.y*e.size.z};return{unit:'un',qty:1}}
function worksFromModel(p:StudioProject):WorkItem[]{let i=1;return p.elements.map(e=>{const q=qUnit(e),code=`${String(i++).padStart(2,'0')}.01`;return{id:`W-${e.id}`,code,chapter:e.category,description:e.name,unit:q.unit,qty:+q.qty.toFixed(3),unitPrice:basePrice[e.type]||120,duration:Math.max(1,Math.ceil(q.qty/15)),start:0,source:e.source}})}
export default function App(){const[page,setPage]=useState<Page>('model'),[project,setProject]=useState<StudioProject>(()=>{try{return JSON.parse(localStorage.getItem('rjp3d:project')||'null')||blank()}catch{return blank()}}),[selected,setSelected]=useState<string|null>(null),[drawings,setDrawings]=useState<SourceDrawing[]>([]),[works,setWorks]=useState<WorkItem[]>(()=>{try{return JSON.parse(localStorage.getItem('rjp3d:works')||'[]')}catch{return[]}}),[measurements,setMeasurements]=useState<Measurement[]>(()=>{try{return JSON.parse(localStorage.getItem('rjp3d:measurements')||'[]')}catch{return[]}});const strutRef=useRef<HTMLInputElement>(null),ifcRef=useRef<HTMLInputElement>(null),drawRef=useRef<HTMLInputElement>(null);const sel=project.elements.find(e=>e.id===selected)||null;const save=(p=project)=>{const x={...p,updatedAt:now()};setProject(x);localStorage.setItem('rjp3d:project',JSON.stringify(x))};const updateEl=(id:string,patch:Partial<StudioElement>)=>save({...project,elements:project.elements.map(e=>e.id===id?{...e,...patch}:e)});const addLib=(id:string)=>{const item=library.find(x=>x.id===id);if(!item)return;const e=createFromLibrary(item,project.elements.length+1);save({...project,elements:[...project.elements,e]});setSelected(e.id);setPage('model')};const generateWorks=(p=project)=>{const w=worksFromModel(p);setWorks(w);localStorage.setItem('rjp3d:works',JSON.stringify(w))};const total=works.reduce((s,w)=>s+w.qty*w.unitPrice,0);const measured=measurements.reduce((s,m)=>{const w=works.find(x=>x.id===m.workId);return s+(w?w.unitPrice*m.current:0)},0)
 async function importStrut(f?:File){if(!f)return;try{const p=JSON.parse(await f.text()) as RJPStudioStructurePackage;if(p.schema!=='RJP-STUDIO-STRUCTURE/1.0')throw new Error('Formato SmartStruct/RJP_3D não reconhecido.');const pr=projectFromStrut(p);save(pr);generateWorks(pr);setPage('model')}catch(e){alert(e instanceof Error?e.message:'Não foi possível importar.')}}
 async function importIfcFile(f?:File){if(!f)return;try{const incoming=projectFromIfc(await f.text(),project);const mode=project.elements.length&&confirm('Atualizar o modelo atual por GUID/ID? OK = atualizar; Cancelar = substituir.');const pr=mode?mergeIfc(project,incoming):incoming;save(pr);generateWorks(pr);setPage('model')}catch(e){alert(e instanceof Error?e.message:'Não foi possível importar o IFC.')}}
 async function addDrawing(f?:File){if(!f)return;const d=await inspectDrawing(f);setDrawings(x=>[...x,d]);setPage('sources')}
 const nav:[Page,string,React.ReactNode][]=[['model','Modelo 3D',<Box/>],['library','Biblioteca',<LibraryBig/>],['sources','Plantas / CAD',<FileUp/>],['mqt','MQT',<Ruler/>],['budget','Orçamento',<WalletCards/>],['planning','Planeamento',<CalendarDays/>],['measurements','Autos',<ClipboardCheck/>],['specs','Caderno Técnico',<ReceiptText/>]]
 return <div className="app"><aside><div className="brand"><b>RJP_3D</b><span>STUDIO</span></div><nav>{nav.map(([id,l,ic])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{ic}<span>{l}</span></button>)}</nav><div className="aside-foot">Modelo · Construção · Obra</div></aside><main><header><div><h1>{project.name}</h1><span>{project.location||'Projeto sem localização'} · {project.elements.length} elementos</span></div><div className="head-actions"><input ref={strutRef} hidden type="file" accept=".json,.rjp3d.json" onChange={e=>importStrut(e.target.files?.[0])}/><input ref={ifcRef} hidden type="file" accept=".ifc" onChange={e=>importIfcFile(e.target.files?.[0])}/><input ref={drawRef} hidden type="file" accept=".pdf,.dwg,.dwf,.dwfx,.png,.jpg,.jpeg,.webp" onChange={e=>addDrawing(e.target.files?.[0])}/><button onClick={()=>ifcRef.current?.click()}><FileUp/> Importar IFC</button><button onClick={()=>downloadIfc(project)}>Exportar IFC</button><button onClick={()=>strutRef.current?.click()} title="Compatibilidade V1.0">Importar legado</button><button onClick={()=>save()}><Save/> Guardar</button></div></header>
 {page==='model'&&<div className="model-layout"><section className="viewer-card"><div className="viewer-head"><div><b>Editor 3D</b><span>Orbit: rato · Zoom: roda · Selecionar: clique · Mover: gizmo</span></div><span className="pill">{project.solution==='traditional'?'Construção tradicional':project.solution==='lsf'?'LSF':'Madeira'}</span></div><ThreeViewport elements={project.elements} selectedId={selected} onSelect={setSelected} onChange={updateEl}/></section><aside className="props"><h3>Propriedades</h3>{sel?<><label>Nome<input value={sel.name} onChange={e=>updateEl(sel.id,{name:e.target.value})}/></label><div className="triple"><label>X<input type="number" step=".05" value={sel.position.x} onChange={e=>updateEl(sel.id,{position:{...sel.position,x:n(e.target.value)}})}/></label><label>Y<input type="number" step=".05" value={sel.position.y} onChange={e=>updateEl(sel.id,{position:{...sel.position,y:n(e.target.value)}})}/></label><label>Z<input type="number" step=".05" value={sel.position.z} onChange={e=>updateEl(sel.id,{position:{...sel.position,z:n(e.target.value)}})}/></label></div><label>Material<select value={sel.material.id} onChange={e=>updateEl(sel.id,{material:materials.find(m=>m.id===e.target.value)||sel.material})}>{materials.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="result-card"><b>{sel.type}</b><span>{sel.source}</span>{sel.results&&Object.entries(sel.results).slice(0,5).map(([k,v])=><small key={k}>{k}: {String(v)}</small>)}</div><div className="row"><button onClick={()=>{const c={...sel,id:`${sel.id}-COPY-${Date.now()}`,name:`${sel.name} cópia`,position:{...sel.position,x:sel.position.x+.5}};save({...project,elements:[...project.elements,c]})}}>Duplicar</button><button className="danger" onClick={()=>{save({...project,elements:project.elements.filter(x=>x.id!==sel.id)});setSelected(null)}}>Apagar</button></div></>:<p className="muted">Selecione um elemento no modelo ou adicione-o pela Biblioteca.</p>}<h3>Sistema construtivo</h3><select value={project.solution} onChange={e=>save({...project,solution:e.target.value as StudioProject['solution']})}><option value="traditional">Tradicional · alvenaria</option><option value="lsf">LSF</option><option value="timber">Madeira / timber frame</option></select></aside></div>}
 {page==='library'&&<section className="page"><div className="page-title"><h2>Biblioteca de Elementos</h2><p>Estrutura, arquitetura, LSF, madeira, coberturas, drenagem, mobiliário e sanitários.</p></div><div className="library-grid">{library.map(i=><article key={i.id}><div className={`swatch ${i.material.texture||''}`}></div><b>{i.name}</b><span>{i.category}</span><small>{i.material.name}</small><button onClick={()=>addLib(i.id)}>Adicionar ao modelo</button></article>)}</div></section>}
 {page==='sources'&&<section className="page"><div className="page-title action-title"><div><h2>Plantas e ficheiros CAD</h2><p>Use PDF como base gráfica. DWG/DWF/DWFx ficam anexados e identificados para o adaptador CAD desktop.</p></div><button onClick={()=>drawRef.current?.click()}><FileUp/> Adicionar ficheiro</button></div><div className="source-grid">{drawings.map(d=><article key={d.id}><b>{d.name}</b><span>{d.kind.toUpperCase()} · {(d.size/1024/1024).toFixed(2)} MB</span><p>{d.info}</p>{d.kind==='pdf'&&d.url&&<iframe src={d.url} title={d.name}/>} {d.kind==='image'&&d.url&&<img src={d.url} alt=""/>}</article>)}</div><div className="notice"><b>DWG/DWF</b><span>A WebApp reconhece e anexa estes ficheiros. A extração/renderização nativa da geometria será feita pelo adaptador CAD da versão Windows (ODA/Autodesk compatível), evitando prometer leitura geométrica incompleta no browser.</span></div></section>}
 {page==='mqt'&&<section className="page"><div className="page-title action-title"><div><h2>Mapa de Quantidades de Trabalho</h2><p>Quantidades extraídas do modelo e editáveis antes do orçamento.</p></div><button onClick={()=>generateWorks()}>Recalcular pelo modelo</button></div><WorkTable works={works} setWorks={x=>{setWorks(x);localStorage.setItem('rjp3d:works',JSON.stringify(x))}} showPrice={false}/></section>}
 {page==='budget'&&<section className="page"><div className="page-title action-title"><div><h2>Orçamento</h2><p>Preços unitários editáveis; valores de referência, fornecedor, adjudicado ou obra podem ser introduzidos pelo utilizador.</p></div><button onClick={()=>window.open('https://geradordeprecos.info/','_blank','noopener,noreferrer')}>Gerador de Preços · referência</button></div><div className="kpis"><K t="Total" v={eur(total)}/><K t="Artigos" v={String(works.length)}/><K t="Executado em autos" v={eur(measured)}/></div><WorkTable works={works} setWorks={x=>{setWorks(x);localStorage.setItem('rjp3d:works',JSON.stringify(x))}} showPrice/></section>}
 {page==='planning'&&<section className="page"><div className="page-title"><h2>Planeamento de Execução</h2><p>Programa simples por atividades, duração e sequência; preparado para evoluir para recursos e curva financeira.</p></div><Gantt works={works}/></section>}
 {page==='measurements'&&<section className="page"><div className="page-title"><h2>Autos de Medição</h2><p>Registe quantidades por artigo, auto e data. O acumulado é comparado com a quantidade contratada.</p></div><div className="measure-grid">{works.map(w=>{const ms=measurements.filter(m=>m.workId===w.id),acc=ms.reduce((s,m)=>s+m.current,0);return <article key={w.id}><b>{w.code} · {w.description}</b><span>Contratado: {w.qty.toFixed(2)} {w.unit} · Acumulado: {acc.toFixed(2)}</span><div className="progress"><i style={{width:`${Math.min(100,100*acc/Math.max(w.qty,.001))}%`}}/></div><button onClick={()=>{const q=Number(prompt(`Quantidade deste auto (${w.unit})`,'0')||0);if(!q)return;const a=Number(prompt('N.º do auto',String((Math.max(0,...measurements.map(m=>m.autoNo)))+1))||1);const m:Measurement={id:`M-${Date.now()}`,workId:w.id,autoNo:a,previous:acc,current:q,date:new Date().toISOString().slice(0,10),note:''};const x=[...measurements,m];setMeasurements(x);localStorage.setItem('rjp3d:measurements',JSON.stringify(x))}}>Medir neste auto</button></article>})}</div></section>}
 {page==='specs'&&<Specs project={project} works={works}/>} </main></div>}
function K({t,v}:{t:string;v:string}){return <div><span>{t}</span><b>{v}</b></div>}
function WorkTable({works,setWorks,showPrice}:{works:WorkItem[];setWorks:(x:WorkItem[])=>void;showPrice:boolean}){const upd=(id:string,k:keyof WorkItem,v:any)=>setWorks(works.map(w=>w.id===id?{...w,[k]:['qty','unitPrice','duration','start'].includes(String(k))?n(v):v}:w));return <div className={`worktable ${showPrice?'with-price':''}`}><div className="workrow head"><b>Código</b><b>Capítulo / Trabalho</b><b>Un.</b><b>Qtd.</b>{showPrice&&<><b>P.U.</b><b>Total</b></>}<b>Dias</b></div>{works.map(w=><div className="workrow" key={w.id}><input value={w.code} onChange={e=>upd(w.id,'code',e.target.value)}/><div><input value={w.chapter} onChange={e=>upd(w.id,'chapter',e.target.value)}/><input value={w.description} onChange={e=>upd(w.id,'description',e.target.value)}/></div><input value={w.unit} onChange={e=>upd(w.id,'unit',e.target.value)}/><input type="number" value={w.qty} onChange={e=>upd(w.id,'qty',e.target.value)}/>{showPrice&&<><input type="number" value={w.unitPrice} onChange={e=>upd(w.id,'unitPrice',e.target.value)}/><b>{eur(w.qty*w.unitPrice)}</b></>}<input type="number" value={w.duration} onChange={e=>upd(w.id,'duration',e.target.value)}/></div>)}</div>}
function Gantt({works}:{works:WorkItem[]}){let cur=0;const items=works.map(w=>{const x={...w,start:w.start||cur};cur=Math.max(cur,x.start+x.duration);return x}),max=Math.max(1,...items.map(w=>w.start+w.duration));return <div className="gantt">{items.map(w=><div key={w.id}><b>{w.code}</b><span>{w.chapter}</span><div><i style={{left:`${100*w.start/max}%`,width:`${Math.max(1,100*w.duration/max)}%`}}/></div><small>{w.duration} d</small></div>)}</div>}
function Specs({project,works}:{project:StudioProject;works:WorkItem[]}){const system=project.solution==='traditional'?['Paredes em alvenaria conforme projeto e fichas de produto.','Argamassas, isolamento, rebocos e revestimentos compatíveis com a solução.','Controlar prumos, planeza, juntas, ligações e proteção à água.']:project.solution==='lsf'?['Perfis LSF galvanizados segundo projeto estrutural.','Placas, membranas, isolamento e fixações conforme solução do fabricante/projeto.','Controlar afastamentos, ancoragens, contraventamento, pontes térmicas e proteção à humidade.']:['Elementos de madeira classificados e protegidos para a classe de serviço.','Camadas de fechamento, isolamento, membranas e fixações compatíveis.','Controlar teor de água, ligações, proteção biológica, fogo e estanquidade.'];return <section className="page"><div className="page-title"><h2>Caderno Técnico · Base Editável</h2><p>Especificações técnicas geradas pela solução escolhida; devem ser revistas pelo projetista antes de integrar peças contratuais.</p></div><article className="spec"><h3>1 · Sistema construtivo</h3>{system.map(x=><p key={x}>{x}</p>)}</article><article className="spec"><h3>2 · Medição e orçamento</h3><p>Os artigos são medidos nas unidades indicadas no MQT. Quantidades finais devem ser conferidas nas peças desenhadas, modelo e obra.</p><p>{works.length} artigos atualmente associados ao projeto.</p></article><article className="spec"><h3>3 · Controlo de execução</h3><p>Registar materiais, fichas técnicas, lotes, inspeções, não conformidades, medições e autos. As tolerâncias e ensaios específicos dependem da solução e normas aplicáveis.</p></article></section>}
