import type {CadSegment,RJPStudioStructurePackage,SourceDrawing,StudioElement,StudioProject} from './types'
import {materials} from './library'
const num=(v:unknown,d=0)=>Number.isFinite(Number(v))?Number(v):d
const node=(p:RJPStudioStructurePackage,id?:number)=>p.nodes.find(n=>n.id===id)
export function projectFromStrut(p:RJPStudioStructurePackage):StudioProject{
 const els:StudioElement[]=[]
 for(const e of p.members){const a=node(p,e.a),b=node(p,e.b);const vertical=e.kind==='column'||(a&&b&&Math.abs(a.x-b.x)<1e-7);const x1=a?.x??0,z1=a?.y??0,x2=b?.x??x1+num(e.geometry.length,1),z2=b?.y??z1;const L=Math.hypot(x2-x1,z2-z1)||num(e.geometry.length,1);els.push({id:e.id,name:e.kind==='column'?`Pilar ${e.id}`:`Viga ${e.id}`,type:e.kind,category:'Estrutura',position:{x:(x1+x2)/2,y:0,z:(z1+z2)/2},rotation:{x:0,y:vertical?0:0,z:vertical?0:Math.atan2(z2-z1,x2-x1)},size:vertical?{x:.35,y:.45,z:L}:{x:L,y:.25,z:.5},material:e.material||materials[0],source:'SmartStruct RJP',properties:{nodeA:e.a??null,nodeB:e.b??null,reinforcement:e.reinforcement??null},results:e.results})}
 for(const f of p.foundations){const n=node(p,f.node),B=num(f.geometry.B_m,1.8),L=num(f.geometry.L_m,B),h=num(f.geometry.h_m,.5);els.push({id:f.id,name:`Fundação ${f.id}`,type:'footing',category:'Estrutura',position:{x:n?.x??0,y:0,z:-h/2},rotation:{x:0,y:0,z:0},size:{x:B,y:L,z:h},material:materials[0],source:'SmartStruct RJP',properties:{node:f.node,reinforcement:f.reinforcement??null,...f.actions},results:f.results})}
 const now=new Date().toISOString();return{id:`RJP-${Date.now()}`,name:String(p.project.name||'Projeto importado'),location:String(p.project.location||''),solution:'traditional',elements:els,createdAt:now,updatedAt:now}
}
function pairs(text:string){const ls=text.replace(/\r/g,'').split('\n'),out:Array<[string,string]>=[];for(let i=0;i+1<ls.length;i+=2)out.push([ls[i].trim(),ls[i+1].trim()]);return out}
export function parseDxf(text:string){const p=pairs(text),segments:CadSegment[]=[];let i=0;while(i<p.length){if(p[i][0]==='0'&&p[i][1]==='LINE'){i++;let layer='0',x1=0,y1=0,x2=0,y2=0;while(i<p.length&&p[i][0]!=='0'){const[c,v]=p[i++];if(c==='8')layer=v;if(c==='10')x1=num(v);if(c==='20')y1=num(v);if(c==='11')x2=num(v);if(c==='21')y2=num(v)};if(Math.hypot(x2-x1,y2-y1)>1e-9)segments.push({x1,y1,x2,y2,layer});continue}
 if(p[i][0]==='0'&&p[i][1]==='LWPOLYLINE'){i++;let layer='0',closed=false;const pts:Array<{x:number;y:number}>=[];let cur:{x:number;y:number}|null=null;while(i<p.length&&p[i][0]!=='0'){const[c,v]=p[i++];if(c==='8')layer=v;if(c==='70')closed=(Number(v)&1)===1;if(c==='10'){cur={x:num(v),y:0};pts.push(cur)}if(c==='20'&&cur)cur.y=num(v)}for(let k=1;k<pts.length;k++)segments.push({x1:pts[k-1].x,y1:pts[k-1].y,x2:pts[k].x,y2:pts[k].y,layer});if(closed&&pts.length>2)segments.push({x1:pts[pts.length-1].x,y1:pts[pts.length-1].y,x2:pts[0].x,y2:pts[0].y,layer});continue}i++}
 const xs=segments.flatMap(s=>[s.x1,s.x2]),ys=segments.flatMap(s=>[s.y1,s.y2]);return{segments,bounds:segments.length?{minX:Math.min(...xs),minY:Math.min(...ys),maxX:Math.max(...xs),maxY:Math.max(...ys)}:undefined}}
export async function inspectDrawing(file:File):Promise<SourceDrawing>{const b=new Uint8Array(await file.slice(0,64).arrayBuffer());const text=new TextDecoder('latin1').decode(b);const ext=file.name.split('.').pop()?.toLowerCase()||'';let kind:SourceDrawing['kind']='other',info='Ficheiro de referência',cadSegments:CadSegment[]|undefined,cadBounds:SourceDrawing['cadBounds'];if(ext==='pdf'||text.startsWith('%PDF')){kind='pdf';info='PDF: pré-visualização direta suportada; pode ser usado como base gráfica para modelação.'}else if(ext==='dxf'){kind='dxf';const parsed=parseDxf(await file.text());cadSegments=parsed.segments;cadBounds=parsed.bounds;info=`DXF ASCII: ${cadSegments.length} segmentos LINE/LWPOLYLINE reconhecidos. Pode gerar paredes BIM a partir desta geometria.`}else if(ext==='dwg'||text.startsWith('AC10')){kind='dwg';info=`DWG ${text.slice(0,6)}: cabeçalho reconhecido; para geometria editável, converta para DXF/IFC ou use o adaptador CAD da versão Windows.`}else if(ext==='dwf'){kind='dwf';info='DWF reconhecido: referência anexada; geometria nativa requer adaptador Autodesk/ODA ou conversão para DXF/IFC.'}else if(ext==='dwfx'){kind='dwfx';info='DWFx reconhecido: pacote XPS/OPC anexado; geometria nativa requer adaptador desktop ou conversão.'}else if(['png','jpg','jpeg','webp'].includes(ext)){kind='image';info='Imagem: pré-visualização direta suportada; pode servir como base gráfica.'}return{id:`DRAW-${Date.now()}`,name:file.name,kind,size:file.size,info,url:URL.createObjectURL(file),cadSegments,cadBounds}}
export function wallsFromCad(d:SourceDrawing,scale=1,height=2.8,thickness=.2):StudioElement[]{const ss=d.cadSegments||[],b=d.cadBounds;if(!ss.length||!b)return[];const mat=materials.find(m=>m.id==='brick')||materials[0];return ss.filter(s=>Math.hypot(s.x2-s.x1,s.y2-s.y1)>1e-6).map((s,i)=>{const x1=(s.x1-b.minX)*scale,y1=(s.y1-b.minY)*scale,x2=(s.x2-b.minX)*scale,y2=(s.y2-b.minY)*scale,L=Math.hypot(x2-x1,y2-y1),a=Math.atan2(y2-y1,x2-x1);return{id:`CAD-WALL-${Date.now()}-${i}`,name:`Parede CAD · ${s.layer}`,type:'wall',category:'Arquitetura',level:'Piso 0',position:{x:(x1+x2)/2,y:(y1+y2)/2,z:height/2},rotation:{x:0,y:0,z:a},size:{x:L,y:thickness,z:height},material:mat,source:`CAD/DXF · ${d.name}`,properties:{cadLayer:s.layer,cadSource:d.name}}})}
