import type {RJPStudioStructurePackage,SourceDrawing,StudioElement,StudioProject} from './types'
import {materials} from './library'
const num=(v:unknown,d=0)=>Number.isFinite(Number(v))?Number(v):d
const node=(p:RJPStudioStructurePackage,id?:number)=>p.nodes.find(n=>n.id===id)
export function projectFromStrut(p:RJPStudioStructurePackage):StudioProject{
 const els:StudioElement[]=[]
 for(const e of p.members){const a=node(p,e.a),b=node(p,e.b);const vertical=e.kind==='column'||(a&&b&&Math.abs(a.x-b.x)<1e-7);const x1=a?.x??0,z1=a?.y??0,x2=b?.x??x1+num(e.geometry.length,1),z2=b?.y??z1;const L=Math.hypot(x2-x1,z2-z1)||num(e.geometry.length,1);els.push({id:e.id,name:e.kind==='column'?`Pilar ${e.id}`:`Viga ${e.id}`,type:e.kind,category:'Estrutura',position:{x:(x1+x2)/2,y:0,z:(z1+z2)/2},rotation:{x:0,y:vertical?0:0,z:vertical?0:Math.atan2(z2-z1,x2-x1)},size:vertical?{x:.35,y:.45,z:L}:{x:L,y:.25,z:.5},material:e.material||materials[0],source:'SmartStruct RJP',properties:{nodeA:e.a??null,nodeB:e.b??null,reinforcement:e.reinforcement??null},results:e.results})}
 for(const f of p.foundations){const n=node(p,f.node),B=num(f.geometry.B_m,1.8),L=num(f.geometry.L_m,B),h=num(f.geometry.h_m,.5);els.push({id:f.id,name:`Fundação ${f.id}`,type:'footing',category:'Estrutura',position:{x:n?.x??0,y:0,z:-h/2},rotation:{x:0,y:0,z:0},size:{x:B,y:L,z:h},material:materials[0],source:'SmartStruct RJP',properties:{node:f.node,reinforcement:f.reinforcement??null,...f.actions},results:f.results})}
 const now=new Date().toISOString();return{id:`RJP-${Date.now()}`,name:String(p.project.name||'Projeto importado'),location:String(p.project.location||''),solution:'traditional',elements:els,createdAt:now,updatedAt:now}
}
export async function inspectDrawing(file:File):Promise<SourceDrawing>{const b=new Uint8Array(await file.slice(0,64).arrayBuffer());const text=new TextDecoder('latin1').decode(b);const ext=file.name.split('.').pop()?.toLowerCase()||'';let kind:SourceDrawing['kind']='other',info='Ficheiro de referência';if(ext==='pdf'||text.startsWith('%PDF')){kind='pdf';info='PDF: pré-visualização direta suportada.'}else if(ext==='dwg'||text.startsWith('AC10')){kind='dwg';info=`DWG ${text.slice(0,6)}: cabeçalho reconhecido; geometria nativa requer adaptador CAD/ODA na versão desktop.`}else if(ext==='dwf'){kind='dwf';info='DWF reconhecido: referência anexada; geometria nativa requer adaptador Autodesk/ODA.'}else if(ext==='dwfx'){kind='dwfx';info='DWFx reconhecido: pacote XPS/OPC anexado; geometria nativa requer adaptador desktop.'}else if(['png','jpg','jpeg','webp'].includes(ext)){kind='image';info='Imagem: pré-visualização direta suportada.'}return{id:`DRAW-${Date.now()}`,name:file.name,kind,size:file.size,info,url:URL.createObjectURL(file)}}
