import type {StudioElement,StudioMaterial} from './types'
export const materials:StudioMaterial[]=[
{id:'conc-c30',name:'Betão C30/37',family:'Betão',texture:'concrete'},
{id:'steel-s275',name:'Aço S275',family:'Aço',texture:'steel'},
{id:'timber-c24',name:'Madeira C24',family:'Madeira',texture:'wood'},
{id:'lsf-z275',name:'LSF Z275',family:'Aço leve',texture:'galvanized'},
{id:'brick',name:'Tijolo cerâmico',family:'Alvenaria',texture:'brick'},
{id:'block',name:'Bloco de betão',family:'Alvenaria',texture:'block'},
{id:'glass',name:'Vidro',family:'Vidro',texture:'glass'},
{id:'tile',name:'Telha cerâmica',family:'Cobertura',texture:'tile'},
{id:'sandwich',name:'Painel sandwich',family:'Cobertura',texture:'sandwich'},
{id:'plaster',name:'Reboco pintado',family:'Revestimento',texture:'plaster'},
{id:'ceramic',name:'Cerâmico',family:'Revestimento',texture:'ceramic'},
{id:'insulation',name:'Isolamento térmico',family:'Isolamento',texture:'insulation'},
{id:'stone',name:'Pedra natural',family:'Revestimento',texture:'stone'},
{id:'gypsum',name:'Placa de gesso',family:'Divisórias',texture:'gypsum'},
{id:'pvc',name:'PVC',family:'Instalações',texture:'pvc'},
{id:'aluminium',name:'Alumínio',family:'Caixilharia',texture:'aluminium'},
{id:'soil',name:'Terreno',family:'Exterior',texture:'soil'}]
const m=(id:string)=>materials.find(x=>x.id===id)!
export interface LibraryItem{id:string;name:string;category:string;type:string;size:{x:number;y:number;z:number};material:StudioMaterial}
export const library:LibraryItem[]=[
{id:'column30',name:'Pilar 30×30',category:'Estrutura',type:'column',size:{x:.3,y:.3,z:3},material:m('conc-c30')},
{id:'column-steel',name:'Pilar metálico HEA',category:'Estrutura',type:'column',size:{x:.25,y:.25,z:3},material:m('steel-s275')},
{id:'beam2550',name:'Viga 25×50',category:'Estrutura',type:'beam',size:{x:5,y:.25,z:.5},material:m('conc-c30')},
{id:'beam-steel',name:'Viga metálica IPE',category:'Estrutura',type:'beam',size:{x:5,y:.18,z:.36},material:m('steel-s275')},
{id:'slab18',name:'Laje 18 cm',category:'Estrutura',type:'slab',size:{x:5,y:4,z:.18},material:m('conc-c30')},
{id:'footing',name:'Sapata isolada',category:'Estrutura',type:'footing',size:{x:1.8,y:1.8,z:.5},material:m('conc-c30')},
{id:'strip-footing',name:'Sapata corrida',category:'Estrutura',type:'footing',size:{x:5,y:.8,z:.4},material:m('conc-c30')},
{id:'wall-brick',name:'Parede tijolo 20 cm',category:'Arquitetura',type:'wall',size:{x:4,y:.2,z:2.8},material:m('brick')},
{id:'wall-brick11',name:'Parede tijolo 11 cm',category:'Arquitetura',type:'wall',size:{x:4,y:.11,z:2.8},material:m('brick')},
{id:'wall-block',name:'Parede bloco 20 cm',category:'Arquitetura',type:'wall',size:{x:4,y:.2,z:2.8},material:m('block')},
{id:'wall-stone',name:'Parede de pedra 50 cm',category:'Reabilitação',type:'wall',size:{x:4,y:.5,z:2.8},material:m('stone')},
{id:'wall-gypsum',name:'Divisória gesso cartonado',category:'Arquitetura',type:'wall',size:{x:4,y:.1,z:2.8},material:m('gypsum')},
{id:'wall-lsf',name:'Parede LSF 15 cm',category:'LSF',type:'wall',size:{x:4,y:.15,z:2.8},material:m('lsf-z275')},
{id:'wall-timber',name:'Parede timber frame',category:'Madeira',type:'wall',size:{x:4,y:.18,z:2.8},material:m('timber-c24')},
{id:'window',name:'Janela 1,20×1,20',category:'Vãos',type:'window',size:{x:1.2,y:.08,z:1.2},material:m('glass')},
{id:'window-wide',name:'Janela 2,40×1,40',category:'Vãos',type:'window',size:{x:2.4,y:.08,z:1.4},material:m('glass')},
{id:'door',name:'Porta 0,90×2,10',category:'Vãos',type:'door',size:{x:.9,y:.06,z:2.1},material:m('timber-c24')},
{id:'sliding-door',name:'Porta de correr 2,40 m',category:'Vãos',type:'door',size:{x:2.4,y:.08,z:2.2},material:m('glass')},
{id:'garage-door',name:'Portão de garagem',category:'Vãos',type:'door',size:{x:2.7,y:.1,z:2.3},material:m('aluminium')},
{id:'roof-tile',name:'Cobertura telha inclinada',category:'Cobertura',type:'roof',size:{x:6,y:8,z:.18},material:m('tile')},
{id:'roof-sandwich',name:'Cobertura painel sandwich',category:'Cobertura',type:'roof',size:{x:6,y:8,z:.12},material:m('sandwich')},
{id:'roof-flat',name:'Cobertura plana',category:'Cobertura',type:'roof',size:{x:6,y:8,z:.22},material:m('insulation')},
{id:'solar',name:'Painel solar',category:'Cobertura',type:'equipment',size:{x:1.75,y:1.1,z:.06},material:m('glass')},
{id:'gutter',name:'Caleira',category:'Drenagem',type:'gutter',size:{x:6,y:.15,z:.15},material:m('steel-s275')},
{id:'downpipe',name:'Tubo de queda Ø110',category:'Drenagem',type:'pipe',size:{x:.11,y:.11,z:3},material:m('pvc')},
{id:'drain',name:'Ralo de cobertura',category:'Drenagem',type:'fixture',size:{x:.25,y:.25,z:.12},material:m('steel-s275')},
{id:'stair',name:'Escada',category:'Arquitetura',type:'stair',size:{x:2.5,y:1.1,z:2.8},material:m('conc-c30')},
{id:'railing',name:'Guarda-corpos',category:'Arquitetura',type:'railing',size:{x:3,y:.06,z:1.05},material:m('glass')},
{id:'floor-tile',name:'Pavimento cerâmico',category:'Acabamentos',type:'floor',size:{x:4,y:4,z:.02},material:m('ceramic')},
{id:'floor-wood',name:'Pavimento madeira',category:'Acabamentos',type:'floor',size:{x:4,y:4,z:.02},material:m('timber-c24')},
{id:'kitchen',name:'Bancada cozinha',category:'Mobiliário',type:'furniture',size:{x:2.4,y:.65,z:.9},material:m('timber-c24')},
{id:'island',name:'Ilha de cozinha',category:'Mobiliário',type:'furniture',size:{x:1.8,y:.9,z:.92},material:m('stone')},
{id:'sofa',name:'Sofá 3 lugares',category:'Mobiliário',type:'furniture',size:{x:2.1,y:.9,z:.85},material:m('timber-c24')},
{id:'bed',name:'Cama casal',category:'Mobiliário',type:'furniture',size:{x:2,y:1.6,z:.55},material:m('timber-c24')},
{id:'table',name:'Mesa jantar',category:'Mobiliário',type:'furniture',size:{x:1.8,y:.9,z:.76},material:m('timber-c24')},
{id:'cabinet',name:'Armário',category:'Mobiliário',type:'furniture',size:{x:1.8,y:.6,z:2.2},material:m('timber-c24')},
{id:'wc',name:'Sanita',category:'Sanitários',type:'fixture',size:{x:.4,y:.65,z:.75},material:m('ceramic')},
{id:'basin',name:'Lavatório',category:'Sanitários',type:'fixture',size:{x:.6,y:.5,z:.85},material:m('ceramic')},
{id:'bath',name:'Banheira',category:'Sanitários',type:'fixture',size:{x:1.7,y:.75,z:.58},material:m('ceramic')},
{id:'shower',name:'Base de duche',category:'Sanitários',type:'fixture',size:{x:1.2,y:.8,z:.08},material:m('ceramic')},
{id:'tap',name:'Torneira',category:'Sanitários',type:'fixture',size:{x:.12,y:.22,z:.32},material:m('steel-s275')},
{id:'water-pipe',name:'Tubagem água Ø25',category:'Instalações',type:'pipe',size:{x:.025,y:.025,z:3},material:m('pvc')},
{id:'drain-pipe',name:'Tubagem esgoto Ø110',category:'Instalações',type:'pipe',size:{x:.11,y:.11,z:3},material:m('pvc')},
{id:'hvac-duct',name:'Conduta AVAC',category:'Instalações',type:'duct',size:{x:2,y:.4,z:.25},material:m('galvanized')},
{id:'elec-panel',name:'Quadro elétrico',category:'Instalações',type:'equipment',size:{x:.5,y:.15,z:.7},material:m('aluminium')},
{id:'tree',name:'Árvore',category:'Exterior',type:'landscape',size:{x:1.2,y:1.2,z:4},material:m('soil')},
{id:'pool',name:'Piscina',category:'Exterior',type:'pool',size:{x:8,y:4,z:1.5},material:m('glass')}
]
export function createFromLibrary(item:LibraryItem,index:number):StudioElement{return{id:`LIB-${item.id}-${index}`,name:item.name,type:item.type,category:item.category,level:'Piso 0',position:{x:0,y:0,z:item.size.z/2},rotation:{x:0,y:0,z:0},size:{...item.size},material:item.material,source:'Biblioteca RJP_3D Studio',properties:{libraryId:item.id},results:undefined}}
