import type {StudioElement,StudioLevel,StudioMaterial,StudioProject} from './types'
import {materials} from './library'
const fallbackMaterial=():StudioMaterial=>materials[0]
const num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d
const vec=(v:any,d:{x:number;y:number;z:number})=>({x:num(v?.x,d.x),y:num(v?.y,d.y),z:num(v?.z,d.z)})
export function normalizeElement(raw:any,index=0):StudioElement{const material=(raw?.material&&typeof raw.material==='object'&&raw.material.id)?raw.material:fallbackMaterial(),size=vec(raw?.size,{x:1,y:1,z:1});return{id:String(raw?.id||`MIG-${Date.now()}-${index}`),name:String(raw?.name||`Elemento ${index+1}`),type:String(raw?.type||'generic'),category:String(raw?.category||'Outros'),level:String(raw?.level||'Piso 0'),position:vec(raw?.position,{x:0,y:0,z:Math.max(.01,size.z)/2}),rotation:vec(raw?.rotation,{x:0,y:0,z:0}),size:{x:Math.max(.001,size.x),y:Math.max(.001,size.y),z:Math.max(.001,size.z)},material,source:String(raw?.source||'Projeto migrado'),properties:(raw?.properties&&typeof raw.properties==='object')?raw.properties:{phase:'Novo'},results:(raw?.results&&typeof raw.results==='object')?raw.results:undefined} as StudioElement}
export function normalizeLevels(raw:any):StudioLevel[]{const fallback:StudioLevel[]=[{id:'L0',name:'Piso 0',elevation:0,height:2.8,visible:true},{id:'L1',name:'Piso 1',elevation:2.8,height:2.8,visible:true},{id:'LC',name:'Cobertura',elevation:5.6,height:2.8,visible:true}];if(!Array.isArray(raw)||!raw.length)return fallback;return raw.map((l:any,i:number)=>({id:String(l?.id||`L${i}`),name:String(l?.name||`Piso ${i}`),elevation:num(l?.elevation,i*2.8),height:Math.max(.2,num(l?.height,2.8)),visible:l?.visible!==false}))}
export function normalizeProject(raw:any):StudioProject{const now=new Date().toISOString();return{id:String(raw?.id||`P-${Date.now()}`),name:String(raw?.name||'Novo Projeto'),location:String(raw?.location||''),solution:(['traditional','lsf','timber'].includes(raw?.solution)?raw.solution:'traditional') as StudioProject['solution'],elements:Array.isArray(raw?.elements)?raw.elements.map(normalizeElement):[],levels:normalizeLevels(raw?.levels),createdAt:String(raw?.createdAt||now),updatedAt:String(raw?.updatedAt||now)} as StudioProject}
export function loadProjectSafe(key='rjp3d:project'):StudioProject|null{try{const text=localStorage.getItem(key);if(!text)return null;const p=normalizeProject(JSON.parse(text));localStorage.setItem(key,JSON.stringify(p));return p}catch(err){console.error('[RJP 3D] projeto guardado inválido',err);return null}}
export function clearRjpLocalData(){for(const k of Object.keys(localStorage))if(k.startsWith('rjp3d:'))localStorage.removeItem(k)}
