import React,{useEffect,useRef} from 'react'
import * as THREE from 'three'
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js'
import {TransformControls} from 'three/examples/jsm/controls/TransformControls.js'
import type {StudioElement} from './types'
const textureColor=(t?:string)=>({concrete:0xb8c0c8,steel:0x8a9aa8,wood:0xa47747,galvanized:0xb7c4cf,brick:0xb15c43,block:0x9ca3a8,glass:0x76c5e8,tile:0xb65a42,sandwich:0x8da3b3,plaster:0xe7e1d5,ceramic:0xe8e8e8,insulation:0xe9d87a}[t||'']||0x7aa8d6)
export default function ThreeViewport({elements,selectedId,onSelect,onChange}:{elements:StudioElement[];selectedId:string|null;onSelect:(id:string|null)=>void;onChange:(id:string,p:Partial<StudioElement>)=>void}){const host=useRef<HTMLDivElement>(null)
 useEffect(()=>{const el=host.current;if(!el)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0x071a2e);const camera=new THREE.PerspectiveCamera(48,1,.05,500);camera.up.set(0,0,1);camera.position.set(12,-16,11);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.innerHTML='';el.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x223344,2.2));const dl=new THREE.DirectionalLight(0xffffff,2.6);dl.position.set(8,-8,15);scene.add(dl);const grid=new THREE.GridHelper(40,40,0x33506d,0x17314b);grid.rotation.x=Math.PI/2;scene.add(grid);const group=new THREE.Group();scene.add(group);const objMap=new Map<string,THREE.Mesh>();for(const e of elements){const geo=new THREE.BoxGeometry(Math.max(.03,e.size.x),Math.max(.03,e.size.y),Math.max(.03,e.size.z));const mat=new THREE.MeshStandardMaterial({color:textureColor(e.material.texture),roughness:.62,metalness:e.material.family.includes('Aço') ? 0.35 : 0.05,transparent:e.type==='window',opacity:e.type==='window' ? 0.55 : 1});const mesh=new THREE.Mesh(geo,mat);mesh.position.set(e.position.x,e.position.y,e.position.z);mesh.rotation.set(e.rotation.x,e.rotation.y,e.rotation.z);mesh.userData.id=e.id;group.add(mesh);objMap.set(e.id,mesh)}
 const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.target.set(3,0,2.5);const tc=new TransformControls(camera,renderer.domElement);scene.add(tc.getHelper());const selected=selectedId?objMap.get(selectedId):undefined;if(selected)tc.attach(selected);tc.addEventListener('dragging-changed',(ev:any)=>orbit.enabled=!ev.value);tc.addEventListener('mouseUp',()=>{const o=tc.object as THREE.Mesh|undefined;if(!o)return;onChange(String(o.userData.id),{position:{x:o.position.x,y:o.position.y,z:o.position.z},rotation:{x:o.rotation.x,y:o.rotation.y,z:o.rotation.z}})});const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();const click=(ev:MouseEvent)=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=((ev.clientX-r.left)/r.width)*2-1;mouse.y=-((ev.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(Array.from(objMap.values()),false)[0];onSelect(hit?String(hit.object.userData.id):null)};renderer.domElement.addEventListener('pointerdown',click);const resize=()=>{const w=el.clientWidth,h=Math.max(420,el.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};resize();const ro=new ResizeObserver(resize);ro.observe(el);let af=0;const loop=()=>{orbit.update();renderer.render(scene,camera);af=requestAnimationFrame(loop)};loop();return()=>{cancelAnimationFrame(af);ro.disconnect();renderer.domElement.removeEventListener('pointerdown',click);orbit.dispose();tc.dispose();renderer.dispose();el.innerHTML=''}},[elements,selectedId])
 return <div className="three-host" ref={host}/>
}
